// Sample property data
export const properties = [
    {
      id: '1',
      image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1000',
      distance: '2.5 km',
      name: 'Opera House',
      type: 'Shared Room',
      description: 'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna.',
      tags: ['Non Alcoholic', 'Fitness Freak'],
      price: '9,599',
      needsCount: '2',
      peopleType: 'Female',
      isFavorite: true,
    },
    {
      id: '2',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000',
      distance: '1.8 km',
      name: 'Lakeside Villa',
      type: 'Rental Home/Flat',
      description: 'Elegant villa with private pool, perfect for families or small groups seeking luxury and privacy.',
      tags: ['Pet Friendly', 'Swimming Pool'],
      price: '12,750',
      needsCount: '3',
      peopleType: 'Male',
      isFavorite: false,
    },
    {
      id: '3',
      image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1000',
      distance: '3.2 km',
      name: 'Urban Loft',
      type: 'PG/Hostel',
      description: 'Modern city apartment with stunning views and contemporary furnishings in downtown area.',
      tags: ['City View', 'Co-working'],
      price: '7,899',
      needsCount: '1',
      peopleType: 'Female',
      isFavorite: true,
    },
    {
      id: '4',
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1000',
      distance: '4.7 km',
      name: 'Beachfront Paradise',
      type: 'Rental Home/Flat',
      description: 'Direct beach access with spacious outdoor area and modern amenities for a perfect vacation.',
      tags: ['Beach Access', 'Non Alcoholic'],
      price: '14,200',
      needsCount: '4',
      peopleType: 'Male',
      isFavorite: false,
    },
    {
      id: '5',
      image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1000',
      distance: '0.9 km',
      name: 'Cozy Cottage',
      type: 'Shared Room',
      description: 'Charming small home with garden and vintage decor, perfect for a peaceful getaway from city life.',
      tags: ['Garden', 'Quiet Area'],
      price: '5,450',
      needsCount: '2',
      peopleType: 'Female',
      isFavorite: true,
    },
  ];